import type { User } from "@/lib/types"

export const sampleUsers: User[] = [
  {
    id: "user1",
    name: "Alex Johnson",
    username: "alexj",
    email: "alex@example.com",
    avatar: "/placeholder.svg?height=100&width=100&text=AJ",
    bio: "Web developer and designer. Coffee enthusiast.",
    followers: 1250,
    following: 350,
    posts: 87,
    createdAt: "2022-01-15T12:00:00Z",
  },
  {
    id: "user2",
    name: "Sam Taylor",
    username: "samtaylor",
    email: "sam@example.com",
    avatar: "/placeholder.svg?height=100&width=100&text=ST",
    bio: "Software engineer at Prism Social. Hiking and photography lover.",
    followers: 3420,
    following: 512,
    posts: 143,
    createdAt: "2022-03-22T09:30:00Z",
  },
  {
    id: "user3",
    name: "Jordan Lee",
    username: "jordanlee",
    email: "jordan@example.com",
    avatar: "/placeholder.svg?height=100&width=100&text=JL",
    bio: "Nature photographer and outdoor enthusiast.",
    followers: 5680,
    following: 425,
    posts: 215,
    createdAt: "2021-11-05T15:45:00Z",
  },
  {
    id: "user4",
    name: "Morgan Chen",
    username: "morganc",
    email: "morgan@example.com",
    avatar: "/placeholder.svg?height=100&width=100&text=MC",
    bio: "AI researcher and tech enthusiast. Building the future.",
    followers: 2890,
    following: 178,
    posts: 92,
    createdAt: "2022-05-18T10:15:00Z",
  },
  {
    id: "user5",
    name: "Taylor Reed",
    username: "taylorreed",
    email: "taylor@example.com",
    avatar: "/placeholder.svg?height=100&width=100&text=TR",
    bio: "Book lover, coffee addict, and aspiring writer.",
    followers: 1780,
    following: 634,
    posts: 76,
    createdAt: "2022-02-28T14:20:00Z",
  },
]

